etunimi = input('Anna etunimi: ')
sukunimi = input('Anna sukunimi: ')
print('Nimeni on', sukunimi + ',', etunimi, sukunimi + '.')
sana1 = input('Anna sana: ')
sana2 = input('Anna toinen sana: ')
print("Sanoista tulee yhdyssana", '\'' + sana1 + sana2 + '\'' + '.')
